runtime: python37
env_variables:
  CLOUD_STORAGE_BUCKET: 'water-noah.appspot.com'
  BUCKET_NAME: 'water-noah.appspot.com'
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50